name: Build and push to docker hub

on:
  push:
    branches:
      - master

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build -t express:latest .
      - name: docker login
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
      - name: push to hub
        run: docker push mwansk77/node-app:latest
