name: Build and publish to docker hub

on:
  push:
    branches: ["master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: build docker image
        run: docker build -t express:latest ./
      - name: docker login
        run: docker login -u "${{secrets.DOCKERHUB_USERNAME}}" -p "${{secrets.DOCKERHUB_PASSWORD}}"
      - name: tag image
        run: docker tag express:latest mwansk77/express-app
      - name: push image to hub
        run: docker push mwansk77/express-app
